name: yelp
channels: !!python/tuple
- defaults
dependencies:
- appnope=0.1.0=py35_0
- attrs=15.2.0=py35_0
- blaze::blaze=0.11.2=py35_0
- blaze::datashape=0.5.3=py35_0
- bokeh=0.12.3=py35_0
- cffi=1.8.3=py35_0
- chest=0.2.3=py35_0
- click=6.6=py35_0
- cloudpickle=0.2.1=py35_0
- cryptography=1.5.2=py35_0
- cssselect=0.9.2=py35_0
- cytoolz=0.8.0=py35_0
- dask=0.11.1=py35_0
- decorator=4.0.10=py35_0
- flask=0.11.1=py35_0
- flask-cors=2.1.2=py35_0
- h5py=2.6.0=np111py35_2
- hdf5=1.8.17=1
- heapdict=1.0.0=py35_1
- idna=2.1=py35_0
- ipython=5.1.0=py35_0
- ipython_genutils=0.1.0=py35_0
- itsdangerous=0.24=py35_0
- jinja2=2.8=py35_1
- libxml2=2.9.2=0
- libxslt=1.1.28=2
- llvmlite=0.14.0=py35_0
- locket=0.2.0=py35_1
- lxml=3.6.4=py35_0
- markupsafe=0.23=py35_2
- mkl=11.3.3=0
- multipledispatch=0.4.9=py35_0
- networkx=1.11=py35_0
- numba=0.29.0=np111py35_0
- numexpr=2.6.1=np111py35_0
- numpy=1.11.2=py35_0
- odo=0.5.0=py35_1
- openssl=1.0.2j=0
- pandas=0.19.0=np111py35_0
- parsel=1.0.2=py35_0
- partd=0.3.6=py35_0
- path.py=8.2.1=py35_0
- pexpect=4.0.1=py35_0
- pickleshare=0.7.4=py35_0
- pip=8.1.2=py35_0
- prompt_toolkit=1.0.3=py35_0
- psutil=4.0.0=py35_0
- ptyprocess=0.5.1=py35_0
- pyasn1=0.1.9=py35_0
- pyasn1-modules=0.0.8=py35_0
- pycparser=2.14=py35_1
- pydispatcher=2.0.5=py35_0
- pygments=2.1.3=py35_0
- pyopenssl=16.0.0=py35_0
- pytables=3.2.3.1=np111py35_0
- python=3.5.2=0
- python-dateutil=2.5.3=py35_0
- python.app=1.2=py35_4
- pytz=2016.7=py35_0
- pyyaml=3.12=py35_0
- queuelib=1.4.2=py35_0
- readline=6.2=2
- requests=2.11.1=py35_0
- scrapy=1.1.1=py35_0
- service_identity=16.0.0=py35_0
- setuptools=27.2.0=py35_0
- simplegeneric=0.8.1=py35_1
- six=1.10.0=py35_0
- sqlalchemy=1.1.2=py35_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- toolz=0.8.0=py35_0
- tornado=4.4.2=py35_0
- traitlets=4.3.1=py35_0
- twisted=16.4.1=py35_0
- w3lib=1.15.0=py35_0
- wcwidth=0.1.7=py35_0
- werkzeug=0.11.11=py35_0
- wheel=0.29.0=py35_0
- xz=5.2.2=0
- yaml=0.1.6=0
- zlib=1.2.8=3
- zope=1.0=py35_0
- zope.interface=4.3.2=py35_0
- pip:
  - fake-useragent==0.1.2
  - ipython-genutils==0.1.0
  - prompt-toolkit==1.0.3
  - scrapy-fake-useragent==1.0.2
  - scrapy-proxies==0.3
  - service-identity==16.0.0
  - tables==3.2.3.1

